# Generated by Django 4.2.6 on 2023-11-01 23:54

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ListingHomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Listing home type',
                'verbose_name_plural': 'Listing home types',
            },
        ),
        migrations.CreateModel(
            name='ListingNeigborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Listing neighborhood',
                'verbose_name_plural': 'Listing neighborhoods',
            },
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Listing status',
                'verbose_name_plural': 'Listing status',
            },
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=listings.models.get_file_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing images',
                'verbose_name_plural': 'Listing images',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='hometype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listinghometype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listingneigborhood'),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listingstatus'),
        ),
    ]
