# Generated by Django 4.2.6 on 2023-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingsModel',
            new_name='Listing',
        ),
    ]
