# Generated by Django 4.2.6 on 2023-12-14 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='property_neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.property_neighborhood'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='property_price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.property_price_range'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.property_type'),
        ),
    ]
